# Generated by Django 4.2 on 2023-07-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_cartproduct_cartproducts_rename_cart_carts'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
