# Generated by Django 4.2 on 2023-07-17 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_rename_category_categories_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='users_favorites',
            field=models.ManyToManyField(related_name='favorites_products', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
