# Generated by Django 4.2 on 2023-07-17 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('cart', '0003_alter_cart_total_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='CartProducts',
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carts',
        ),
    ]
